version: "3.8"
services:
  jbc-validator:
    container_name: jbc-validator
    image: sigp/lighthouse
    user: root
    volumes:
      - ./data/lighthouse:/root/.lighthouse
      - ./config:/config
    command:
      - lighthouse
      - vc
      - --beacon-nodes=${PUBLIC_BEACON_NODE}
      - --testnet-dir=/config
      - --init-slashing-protection
      - --graffiti=${NODE_GRAFFITI}
      - --suggested-fee-recipient=${FEE_RECIPIENT}
      - --debug-level=info
      - --http-allow-origin=*
      - --unencrypted-http-transport     
      - --http 
      - --http-address=0.0.0.0 
      - --http-port=5062      
    ports:
      - 5062:5062 
